### ISSUE TITLE
Re-authorise in the background, and pick up the new refresh token

### ISSUE THREAD

**Issue by cmenon12** [cmenon12/birdbox-livestream#7]
In testing mode (for the API client), the refresh `token.pickle` expires after a week. Need to be able to reauthorise the `token.pickle` file manually in the background (e.g. after 5 days) and have the main Python script pick up the new file and keep running with it. 

Write a new basic script that can reauthorise and save it, and test that the main script picks up this new file automatically (e.g. by checking the expiry date/time). Might need to force it to read the `token.pickle` file every time.

**Comment by cmenon12** [comment]
Issue is still present. Need to adjust the authorisation function to reload the token from the file if this exception occurs.

```python
Traceback (most recent call last):
File "yt_livestream.py", line 755, in main
yt.start_broadcast(start_time)
File "yt_livestream.py", line 361, in start_broadcast
broadcast = self.execute_request(self.service.liveBroadcasts().bind(
File "yt_livestream.py", line 189, in execute_request
response = request.execute()
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
return wrapped(*args, **kwargs)
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/googleapiclient/http.py", line 922, in execute
resp, content = _retry_request(
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/googleapiclient/http.py", line 190, in _retry_request
resp, content = http.request(uri, method, *args, **kwargs)
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/google_auth_httplib2.py", line 209, in request
self.credentials.before_request(self._request, method, uri, request_headers)
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/google/auth/credentials.py", line 133, in before_request
self.refresh(request)
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/google/oauth2/credentials.py", line 302, in refresh
) = reauth.refresh_grant(
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/google/oauth2/reauth.py", line 347, in refresh_grant
_client._handle_error_response(response_data)
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})
```

**Comment by cmenon12** [comment]
Could a possible solution to this be to push the user to re-authorise when the token has expired, as requested in #10?
