### ISSUE TITLE
Resolve the issue of transitioning a broadcast to live when the stream is inactive

### ISSUE THREAD

**Issue by cmenon12** [cmenon12/birdbox-livestream#99]
Should probably wait and retry a few times, is likely to be inactive due to a blip in the Wi-Fi.

```
Traceback (most recent call last):
File "/home/pi/Documents/birdbox-livestream/yt_livestream.py", line 263, in start_broadcast
broadcast: yt_types.YouTubeLiveBroadcast = self.execute_request(
File "/home/pi/Documents/birdbox-livestream/google_services.py", line 180, in execute_request
response = request.execute()
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
return wrapped(*args, **kwargs)
File "/home/pi/.pyenv/versions/3.8.12/lib/python3.8/site-packages/googleapiclient/http.py", line 938, in execute
raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/liveBroadcasts/transition?broadcastStatus=live&id=pFA7v8_3ucM&part=id%2Csnippet%2CcontentDetails%2Cstatus&alt=json returned "Stream is inactive". Details: "[{'message': 'Stream is inactive', 'domain': 'youtube.liveBroadcast', 'reason': 'errorStreamInactive', 'extendedHelp': '[https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition'}]](https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition'%7D])">

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/pi/Documents/birdbox-livestream/yt_livestream.py", line 771, in main
process_broadcasts(now, yt)
File "/home/pi/Documents/birdbox-livestream/yt_livestream.py", line 717, in process_broadcasts
yt.start_broadcast(start_time)
File "/home/pi/Documents/birdbox-livestream/yt_livestream.py", line 278, in start_broadcast
raise googleapiclient.errors.HttpError(
googleapiclient.errors.HttpError: <HttpError 403 when requesting None returned "Stream is inactive". Details: "[{'message': 'Stream is inactive', 'domain': 'youtube.liveBroadcast', 'reason': 'errorStreamInactive', 'extendedHelp': '[https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition'}]](https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition'%7D])">
```

**Comment by cmenon12** [comment]
Not needed, this error is already caught and retried five times in `execute_request()`
